// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWiCxOYlAqzpU9v_P8KdSuPs_EqSgUqI',
    appId: '1:957728152699:web:9146a6d5dc2ddb81ebd6de',
    messagingSenderId: '957728152699',
    projectId: 'fruit-hub-d4c3c',
    authDomain: 'fruit-hub-d4c3c.firebaseapp.com',
    storageBucket: 'fruit-hub-d4c3c.firebasestorage.app',
    measurementId: 'G-TP8BEGT4MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyoiFLtfX-nOJq3FnqjF_wA1wknb5vN_Y',
    appId: '1:957728152699:android:c34b18f23a631fc9ebd6de',
    messagingSenderId: '957728152699',
    projectId: 'fruit-hub-d4c3c',
    storageBucket: 'fruit-hub-d4c3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTzG8V_OawJ6UhoEDRu3gVkjVwADXn7EA',
    appId: '1:957728152699:ios:c9a770ab9df382d5ebd6de',
    messagingSenderId: '957728152699',
    projectId: 'fruit-hub-d4c3c',
    storageBucket: 'fruit-hub-d4c3c.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTzG8V_OawJ6UhoEDRu3gVkjVwADXn7EA',
    appId: '1:957728152699:ios:c9a770ab9df382d5ebd6de',
    messagingSenderId: '957728152699',
    projectId: 'fruit-hub-d4c3c',
    storageBucket: 'fruit-hub-d4c3c.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );
}
